### PR TITLE
#29 Better handling of generics

### PR DESCRIPTION
**Pull request by vajda**
Hi Joachim, 
We've been using jTransfo in our spring project for over a year now and found it very helpful. However, there is little piece missing, automatic conversion of types within lists. I've implemented it. It work both ways, from 'domain' to 'to', and from 'to' to 'domain'. Hope you like it and merge it.

### CODE REVIEW

**Comment by marcoeig** [comment]
I haven't been using jTransfo in a while, but does it mean that we don't have to implement a `Converter` and annotate List properties like so `@MappedBy(typeConverter = "voiceContactList")` anymore?

**Comment by vajda** [comment]
Yes, with this change should be possible to automatically convert lists.

**Comment by joachimvda** [comment]
Dear Vladimir,

Thanks for doing this, great.
I will review the code tomorrow.

Kind regards,
Joachim

**Comment by joachimvda** [comment]
Great contribution, thank you

**Comment by vajda** [comment]
Thanks Joachim. Can you tell me when can I expect 0.16 version?

**Comment by joachimvda** [comment]
Not.
I will release this as soon as I can, but as the API is broken, it will be 1.0. I will let you know when it is out.

**Comment by vajda** [comment]
Ok. Thank you.

**Comment by joachimvda** [comment]
Release has been built. It could take a couple of hours while before it is synced with central.

**Comment by vajda** [comment]
Thanks a lot Joachim!

**Pull request merged**
